# Generated by Django 2.2.5 on 2019-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('coordinates', models.CharField(help_text='use literal _eval() to convert string to tuple', max_length=25)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('n', models.IntegerField(default=-1)),
                ('s', models.IntegerField(default=-1)),
                ('e', models.IntegerField(default=-1)),
                ('w', models.IntegerField(default=-1)),
            ],
        ),
    ]
